name: send-backlog
on:
  issues:
    types: [opened, edited]

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - uses: ./
      env:
        projectid: ${{ secrets.PROJECTID }}
        issuetypeid: ${{ secrets.ISSUETYPEID }}
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        priorityid: 1
        summary: ${{ steps.issue.outputs.title }}